package pe.gob.inei.generadorinei.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "HOGAR".
 */
@Entity
public class Hogar_g {

    @Id(autoincrement = true)
    private Long id;
    private String id_vivienda;
    private String numero_hogar;
    private String nom_ape;
    private String estado;
    private String nropersonas;
    private String vive;
    private String nroviven;
    private String principal;
    private String cobertura;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Hogar_g() {
    }

    public Hogar_g(Long id) {
        this.id = id;
    }

    @Generated
    public Hogar_g(Long id, String id_vivienda, String numero_hogar, String nom_ape, String estado, String nropersonas, String vive, String nroviven, String principal, String cobertura) {
        this.id = id;
        this.id_vivienda = id_vivienda;
        this.numero_hogar = numero_hogar;
        this.nom_ape = nom_ape;
        this.estado = estado;
        this.nropersonas = nropersonas;
        this.vive = vive;
        this.nroviven = nroviven;
        this.principal = principal;
        this.cobertura = cobertura;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getId_vivienda() {
        return id_vivienda;
    }

    public void setId_vivienda(String id_vivienda) {
        this.id_vivienda = id_vivienda;
    }

    public String getNumero_hogar() {
        return numero_hogar;
    }

    public void setNumero_hogar(String numero_hogar) {
        this.numero_hogar = numero_hogar;
    }

    public String getNom_ape() {
        return nom_ape;
    }

    public void setNom_ape(String nom_ape) {
        this.nom_ape = nom_ape;
    }

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public String getNropersonas() {
        return nropersonas;
    }

    public void setNropersonas(String nropersonas) {
        this.nropersonas = nropersonas;
    }

    public String getVive() {
        return vive;
    }

    public void setVive(String vive) {
        this.vive = vive;
    }

    public String getNroviven() {
        return nroviven;
    }

    public void setNroviven(String nroviven) {
        this.nroviven = nroviven;
    }

    public String getPrincipal() {
        return principal;
    }

    public void setPrincipal(String principal) {
        this.principal = principal;
    }

    public String getCobertura() {
        return cobertura;
    }

    public void setCobertura(String cobertura) {
        this.cobertura = cobertura;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
