package pe.gob.inei.generadorinei.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "RESIDENTE".
 */
@Entity
public class Residente_g {

    @Id(autoincrement = true)
    private Long id;
    private String id_vivienda;
    private String numero_hogar;
    private String numero_residente;
    private String numero_informante;
    private String c2_p202;
    private String c2_p203;
    private String c2_p204;
    private String c2_p205_a;
    private String c2_p205_m;
    private String c2_p206;
    private String c2_p207;
    private String cobertura;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Residente_g() {
    }

    public Residente_g(Long id) {
        this.id = id;
    }

    @Generated
    public Residente_g(Long id, String id_vivienda, String numero_hogar, String numero_residente, String numero_informante, String c2_p202, String c2_p203, String c2_p204, String c2_p205_a, String c2_p205_m, String c2_p206, String c2_p207, String cobertura) {
        this.id = id;
        this.id_vivienda = id_vivienda;
        this.numero_hogar = numero_hogar;
        this.numero_residente = numero_residente;
        this.numero_informante = numero_informante;
        this.c2_p202 = c2_p202;
        this.c2_p203 = c2_p203;
        this.c2_p204 = c2_p204;
        this.c2_p205_a = c2_p205_a;
        this.c2_p205_m = c2_p205_m;
        this.c2_p206 = c2_p206;
        this.c2_p207 = c2_p207;
        this.cobertura = cobertura;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getId_vivienda() {
        return id_vivienda;
    }

    public void setId_vivienda(String id_vivienda) {
        this.id_vivienda = id_vivienda;
    }

    public String getNumero_hogar() {
        return numero_hogar;
    }

    public void setNumero_hogar(String numero_hogar) {
        this.numero_hogar = numero_hogar;
    }

    public String getNumero_residente() {
        return numero_residente;
    }

    public void setNumero_residente(String numero_residente) {
        this.numero_residente = numero_residente;
    }

    public String getNumero_informante() {
        return numero_informante;
    }

    public void setNumero_informante(String numero_informante) {
        this.numero_informante = numero_informante;
    }

    public String getC2_p202() {
        return c2_p202;
    }

    public void setC2_p202(String c2_p202) {
        this.c2_p202 = c2_p202;
    }

    public String getC2_p203() {
        return c2_p203;
    }

    public void setC2_p203(String c2_p203) {
        this.c2_p203 = c2_p203;
    }

    public String getC2_p204() {
        return c2_p204;
    }

    public void setC2_p204(String c2_p204) {
        this.c2_p204 = c2_p204;
    }

    public String getC2_p205_a() {
        return c2_p205_a;
    }

    public void setC2_p205_a(String c2_p205_a) {
        this.c2_p205_a = c2_p205_a;
    }

    public String getC2_p205_m() {
        return c2_p205_m;
    }

    public void setC2_p205_m(String c2_p205_m) {
        this.c2_p205_m = c2_p205_m;
    }

    public String getC2_p206() {
        return c2_p206;
    }

    public void setC2_p206(String c2_p206) {
        this.c2_p206 = c2_p206;
    }

    public String getC2_p207() {
        return c2_p207;
    }

    public void setC2_p207(String c2_p207) {
        this.c2_p207 = c2_p207;
    }

    public String getCobertura() {
        return cobertura;
    }

    public void setCobertura(String cobertura) {
        this.cobertura = cobertura;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
