package pe.gob.inei.generadorinei.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "VISITA_ENCUESTADOR".
 */
@Entity
public class Visita_encuestador {

    @Id(autoincrement = true)
    private Long id;
    private String id_vivienda;
    private String numero_hogar;
    private String numero_visita;
    private String vis_fecha_dd;
    private String vis_fecha_mm;
    private String vis_fecha_aa;
    private String vis_hor_ini;
    private String vis_min_ini;
    private String vis_hor_fin;
    private String vis_min_fin;
    private String prox_vis_fecha_dd;
    private String prox_vis_fecha_mm;
    private String prox_vis_fecha_aa;
    private String prox_vis_hor;
    private String prox_vis_min;
    private String vis_resu;
    private String vis_resu_esp;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Visita_encuestador() {
    }

    public Visita_encuestador(Long id) {
        this.id = id;
    }

    @Generated
    public Visita_encuestador(Long id, String id_vivienda, String numero_hogar, String numero_visita, String vis_fecha_dd, String vis_fecha_mm, String vis_fecha_aa, String vis_hor_ini, String vis_min_ini, String vis_hor_fin, String vis_min_fin, String prox_vis_fecha_dd, String prox_vis_fecha_mm, String prox_vis_fecha_aa, String prox_vis_hor, String prox_vis_min, String vis_resu, String vis_resu_esp) {
        this.id = id;
        this.id_vivienda = id_vivienda;
        this.numero_hogar = numero_hogar;
        this.numero_visita = numero_visita;
        this.vis_fecha_dd = vis_fecha_dd;
        this.vis_fecha_mm = vis_fecha_mm;
        this.vis_fecha_aa = vis_fecha_aa;
        this.vis_hor_ini = vis_hor_ini;
        this.vis_min_ini = vis_min_ini;
        this.vis_hor_fin = vis_hor_fin;
        this.vis_min_fin = vis_min_fin;
        this.prox_vis_fecha_dd = prox_vis_fecha_dd;
        this.prox_vis_fecha_mm = prox_vis_fecha_mm;
        this.prox_vis_fecha_aa = prox_vis_fecha_aa;
        this.prox_vis_hor = prox_vis_hor;
        this.prox_vis_min = prox_vis_min;
        this.vis_resu = vis_resu;
        this.vis_resu_esp = vis_resu_esp;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getId_vivienda() {
        return id_vivienda;
    }

    public void setId_vivienda(String id_vivienda) {
        this.id_vivienda = id_vivienda;
    }

    public String getNumero_hogar() {
        return numero_hogar;
    }

    public void setNumero_hogar(String numero_hogar) {
        this.numero_hogar = numero_hogar;
    }

    public String getNumero_visita() {
        return numero_visita;
    }

    public void setNumero_visita(String numero_visita) {
        this.numero_visita = numero_visita;
    }

    public String getVis_fecha_dd() {
        return vis_fecha_dd;
    }

    public void setVis_fecha_dd(String vis_fecha_dd) {
        this.vis_fecha_dd = vis_fecha_dd;
    }

    public String getVis_fecha_mm() {
        return vis_fecha_mm;
    }

    public void setVis_fecha_mm(String vis_fecha_mm) {
        this.vis_fecha_mm = vis_fecha_mm;
    }

    public String getVis_fecha_aa() {
        return vis_fecha_aa;
    }

    public void setVis_fecha_aa(String vis_fecha_aa) {
        this.vis_fecha_aa = vis_fecha_aa;
    }

    public String getVis_hor_ini() {
        return vis_hor_ini;
    }

    public void setVis_hor_ini(String vis_hor_ini) {
        this.vis_hor_ini = vis_hor_ini;
    }

    public String getVis_min_ini() {
        return vis_min_ini;
    }

    public void setVis_min_ini(String vis_min_ini) {
        this.vis_min_ini = vis_min_ini;
    }

    public String getVis_hor_fin() {
        return vis_hor_fin;
    }

    public void setVis_hor_fin(String vis_hor_fin) {
        this.vis_hor_fin = vis_hor_fin;
    }

    public String getVis_min_fin() {
        return vis_min_fin;
    }

    public void setVis_min_fin(String vis_min_fin) {
        this.vis_min_fin = vis_min_fin;
    }

    public String getProx_vis_fecha_dd() {
        return prox_vis_fecha_dd;
    }

    public void setProx_vis_fecha_dd(String prox_vis_fecha_dd) {
        this.prox_vis_fecha_dd = prox_vis_fecha_dd;
    }

    public String getProx_vis_fecha_mm() {
        return prox_vis_fecha_mm;
    }

    public void setProx_vis_fecha_mm(String prox_vis_fecha_mm) {
        this.prox_vis_fecha_mm = prox_vis_fecha_mm;
    }

    public String getProx_vis_fecha_aa() {
        return prox_vis_fecha_aa;
    }

    public void setProx_vis_fecha_aa(String prox_vis_fecha_aa) {
        this.prox_vis_fecha_aa = prox_vis_fecha_aa;
    }

    public String getProx_vis_hor() {
        return prox_vis_hor;
    }

    public void setProx_vis_hor(String prox_vis_hor) {
        this.prox_vis_hor = prox_vis_hor;
    }

    public String getProx_vis_min() {
        return prox_vis_min;
    }

    public void setProx_vis_min(String prox_vis_min) {
        this.prox_vis_min = prox_vis_min;
    }

    public String getVis_resu() {
        return vis_resu;
    }

    public void setVis_resu(String vis_resu) {
        this.vis_resu = vis_resu;
    }

    public String getVis_resu_esp() {
        return vis_resu_esp;
    }

    public void setVis_resu_esp(String vis_resu_esp) {
        this.vis_resu_esp = vis_resu_esp;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
